---
apiVersion: cdi.kubevirt.io/v1beta1
kind: VolumeImportSource
metadata:
  name: cirros-source
  namespace: drtest
spec:
  source:
    registry:
      url: "docker://quay.io/containerdisks/fedora:latest"
