# PVC based test vm.
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: vm
    spec:
      domain:
        devices:
          disks:
            - name: root-disk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - bridge: {}
              masquerade: null
              macAddress: '02:3c:0f:b5:e2:c2'
              model: virtio
              name: nic-ivory-marten-68
              state: up
        resources:
          requests:
            # See https://github.com/cirros-dev/cirros/issues/53
            memory: 4Gi
      networks:
        - multus:
            networkName: default/nad-vlan101
          name: nic-ivory-marten-68
      volumes:
        - name: root-disk
          persistentVolumeClaim:
            claimName: root-disk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: 4q8x-7ri1-usnl
              chpasswd: { expire: False }
          name: cloudinitdisk
